name: Build and deploy to Azure Spring Cloud

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Login to Azure Spring Cloud
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Install Azure Spring Cloud extension
        run: az extension add -y --name spring-cloud
      - name: Pwd
        run: pwd
      - name: LL
        run: ll
      - name: Deploy to Azure Spring Cloud
        run: az spring-cloud app deploy --resource-group spring-piggy --service spring-cloud-piggy --name gateway --jar-path gateway/build/libs/gateway-0.0.1-SNAPSHOT.jar